### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by 2600box** [hayabhay/whisper-ui#72]
Having trouble to get this working on Windows. Any ideas?

Python 3.9.4

```
(venv) PS C:\Users\tiki\Documents\Transcription\frogbase> streamlit run ui/01_🏠_Home.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.0.0.156:8501

2023-09-19 10:45:53.943 Uncaught app exception
Traceback (most recent call last):
  File "c:\users\tiki\documents\transcription\frogbase\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\tiki\Documents\Transcription\frogbase\ui\01_🏠_Home.py", line 13, in <module>
    init_session(st.session_state)
  File "ui\config.py", line 60, in init_session
    from frogbase import FrogBase
  File "C:\Users\tiki\Documents\Transcription\frogbase\frogbase\__init__.py", line 1, in <module>
    from .core import FrogBase
  File "C:\Users\tiki\Documents\Transcription\frogbase\frogbase\core.py", line 13, in <module>
    from frogbase.captions import Captions
  File "C:\Users\tiki\Documents\Transcription\frogbase\frogbase\captions.py", line 17, in <module>
    class Captions(BaseModel):
  File "C:\Users\tiki\Documents\Transcription\frogbase\frogbase\captions.py", line 42, in Captions
    settings: dict | None = Field(default=None, description="The settings under which these captions were generated.")
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by BenLikeCode** [comment]
same here

**Comment by neomars** [comment]
Same here with python 2.7 and 3.9
